const SOMENTE_GRAVADA = 19;
const CRIADA = 20;
const AGUARDANDO_PLANNING_BBIP = 121;
const AGUARDANDO_PLANNING_BACK = 123;
const AGUARDANDO_PLANNING_OTNP = 124;
const BUDGET_INVIAVEL = 125;
const EM_ANDAMENTO = 21;
const AGUARDANDO_ATIVACAO = 22;
const CANCELADA = 23;
const CONCLUIDA = 25;
const SUSPENSA = 24;
const ATENDIDA_PARCIALMENTE = 54;
const EM_CANCELAMENTO = 64;
const SALVAR = "criar OT";
const ENCAMINHAR_DEMANDA = "Encaminhar Demanda";
const INVIABILIZAR_DEMANDA = "Inviabilizar Demanda";
const CANCELAR_OT_DEMANDANTE = "Cancelar OT Demandante";
const CANCELAR_OT = "Cancelar OT";
const ROTEAR_ENGENHARIA = "Enviar Engenharia";
const INCLUIR_SOLUCAO = "Incluir Solucao";
const ATIVAR_SOLUCAO = "Ativar Solucao";
const CONCLUIR_SOLUCAO = "Concluir Solucao";
const SUSPENDER_OT = "Suspender OT";
const RETORNAR_OT = "Retornar OT";
const SOLICTAR_CANCELAR_OT = "Solicitar Cancelamento";
const REJEITAR_CANCELAR_OT = "Rejeitar Cancelamento";

const STATES = [
  SOMENTE_GRAVADA,
  CRIADA,
  AGUARDANDO_PLANNING_BBIP,
  AGUARDANDO_PLANNING_BACK,
  AGUARDANDO_PLANNING_OTNP,
  BUDGET_INVIAVEL,
  EM_ANDAMENTO,
  AGUARDANDO_ATIVACAO,
  CANCELADA,
  CONCLUIDA,
  SUSPENSA,
  ATENDIDA_PARCIALMENTE,
  EM_CANCELAMENTO
];

const EVENTS = [
  SALVAR,
  ENCAMINHAR_DEMANDA,
  INVIABILIZAR_DEMANDA,
  CANCELAR_OT,
  ROTEAR_ENGENHARIA,
  INCLUIR_SOLUCAO,
  ATIVAR_SOLUCAO,
  CONCLUIR_SOLUCAO,
  SUSPENDER_OT,
  RETORNAR_OT,
  SOLICTAR_CANCELAR_OT
];

export const OTTRANSITIONS = [
  { de: SOMENTE_GRAVADA, para: SOMENTE_GRAVADA, transicao: SALVAR },
  { de: SOMENTE_GRAVADA, para: CRIADA, transicao: ENCAMINHAR_DEMANDA },
  { de: SOMENTE_GRAVADA, para: EM_ANDAMENTO, transicao: ENCAMINHAR_DEMANDA },
  { de: SOMENTE_GRAVADA, para: CANCELADA, transicao: CANCELAR_OT_DEMANDANTE },
  { de: EM_ANDAMENTO, para: CANCELADA, transicao: CANCELAR_OT_DEMANDANTE },
  { de: CRIADA, para: AGUARDANDO_PLANNING_BBIP, transicao: ENCAMINHAR_DEMANDA },
  { de: CRIADA, para: AGUARDANDO_PLANNING_BACK, transicao: ENCAMINHAR_DEMANDA },
  { de: CRIADA, para: AGUARDANDO_PLANNING_OTNP, transicao: ENCAMINHAR_DEMANDA },
  { de: CRIADA, para: CANCELADA, transicao: CANCELAR_OT_DEMANDANTE },
  {
    de: AGUARDANDO_PLANNING_BBIP,
    para: BUDGET_INVIAVEL,
    transicao: INVIABILIZAR_DEMANDA
  },
  {
    de: AGUARDANDO_PLANNING_BACK,
    para: BUDGET_INVIAVEL,
    transicao: INVIABILIZAR_DEMANDA
  },
  {
    de: AGUARDANDO_PLANNING_OTNP,
    para: BUDGET_INVIAVEL,
    transicao: INVIABILIZAR_DEMANDA
  },

  {
    de: BUDGET_INVIAVEL,
    para: AGUARDANDO_PLANNING_BBIP,
    transicao: ENCAMINHAR_DEMANDA
  },
  {
    de: BUDGET_INVIAVEL,
    para: AGUARDANDO_PLANNING_BACK,
    transicao: ENCAMINHAR_DEMANDA
  },
  {
    de: BUDGET_INVIAVEL,
    para: AGUARDANDO_PLANNING_OTNP,
    transicao: ENCAMINHAR_DEMANDA
  },
  { de: BUDGET_INVIAVEL, para: CANCELADA, transicao: CANCELAR_OT_DEMANDANTE },

  {
    de: AGUARDANDO_PLANNING_BBIP,
    para: EM_ANDAMENTO,
    transicao: ROTEAR_ENGENHARIA
  },
  {
    de: AGUARDANDO_PLANNING_BBIP,
    para: AGUARDANDO_PLANNING_BACK,
    transicao: ROTEAR_ENGENHARIA
  },
  {
    de: AGUARDANDO_PLANNING_BBIP,
    para: AGUARDANDO_PLANNING_OTNP,
    transicao: ROTEAR_ENGENHARIA
  },

  {
    de: AGUARDANDO_PLANNING_BACK,
    para: EM_ANDAMENTO,
    transicao: ROTEAR_ENGENHARIA
  },
  {
    de: AGUARDANDO_PLANNING_BACK,
    para: AGUARDANDO_PLANNING_BBIP,
    transicao: ROTEAR_ENGENHARIA
  },
  {
    de: AGUARDANDO_PLANNING_BACK,
    para: AGUARDANDO_PLANNING_OTNP,
    transicao: ROTEAR_ENGENHARIA
  },

  {
    de: AGUARDANDO_PLANNING_OTNP,
    para: EM_ANDAMENTO,
    transicao: ROTEAR_ENGENHARIA
  },
  {
    de: AGUARDANDO_PLANNING_OTNP,
    para: AGUARDANDO_PLANNING_BBIP,
    transicao: ROTEAR_ENGENHARIA
  },
  {
    de: AGUARDANDO_PLANNING_OTNP,
    para: AGUARDANDO_PLANNING_BACK,
    transicao: ROTEAR_ENGENHARIA
  },

  { de: EM_ANDAMENTO, para: AGUARDANDO_ATIVACAO, transicao: INCLUIR_SOLUCAO },
  { de: EM_ANDAMENTO, para: SUSPENSA, transicao: SUSPENDER_OT },
  { de: EM_ANDAMENTO, para: EM_CANCELAMENTO, transicao: SOLICTAR_CANCELAR_OT },
  { de: EM_CANCELAMENTO, para: EM_ANDAMENTO, transicao: REJEITAR_CANCELAR_OT },

  {
    de: AGUARDANDO_ATIVACAO,
    para: ATENDIDA_PARCIALMENTE,
    transicao: ATIVAR_SOLUCAO
  },
  { de: AGUARDANDO_ATIVACAO, para: SUSPENSA, transicao: SUSPENDER_OT },
  { de: ATENDIDA_PARCIALMENTE, para: CONCLUIDA, transicao: CONCLUIR_SOLUCAO },
  { de: ATENDIDA_PARCIALMENTE, para: SUSPENSA, transicao: SUSPENDER_OT },
  { de: SUSPENSA, para: AGUARDANDO_ATIVACAO, transicao: RETORNAR_OT },
  { de: SUSPENSA, para: EM_ANDAMENTO, transicao: RETORNAR_OT },
  { de: SUSPENSA, para: ATENDIDA_PARCIALMENTE, transicao: RETORNAR_OT },
  { de: SUSPENSA, para: EM_CANCELAMENTO, transicao: SOLICTAR_CANCELAR_OT },
  { de: EM_CANCELAMENTO, para: CANCELADA, transicao: CANCELAR_OT }
];
